# This file contains the common set of parameters import a set of time series
# CRIRES+ exoplanet atmosphere observations and prepare a cleaned and regridded
# datacube.
#
# YAML specifications: https://yaml.org/spec/1.2.2/
#
#------------------------------------------------------------------------------
# Raw data
#------------------------------------------------------------------------------
# Save path
save_path: ""
star_name: "wasp107"

# Properties CSV with star, planet, and system info
planet_properties_file: "scripts_transit/planet_data_wasp107.csv"

# Data directories where each folder contains observations for a single transit
planet_root_dirs:
 - "/Users/arains/data/WASP107_piskunov_march/wasp107b_N1_20220310/"
 - "/Users/arains/data/WASP107_piskunov_march/wasp107b_N2_20230222/"

# Number of transits
n_transit: 2

# Wildcard to use when loading in time series--this determines whether we load
# blaze corrected spectra or not.
nod_ab_wildcard: "cr2res_obs_nodding_extracted[AB]_blaze_corr.fits"

#------------------------------------------------------------------------------
# Regrid settings
#------------------------------------------------------------------------------
reference_nod_pos: "A"

# Range and step size in km/s for the regridding cross-correlation
cc_range_kms: [-20, 20]
cc_step_kms: 0.1

# Sigma clipping settings for the cross-correlation
do_sigma_clipping: True
sigma_clip_level_upper: 3
sigma_clip_level_lower: 3

# Whether to plot diagnostic plots of CC value as a function of RV shift
make_debug_plots: False

# What method to use for interpolating the template and data. Can be one of: 
# [‘linear’, ‘nearest’, ‘nearest-up’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’,
#  ‘previous’, or ‘next’].
interpolation_method: "cubic"

# If True, then we only do a single cross-correlation per detector
do_rigid_regrid_per_detector: True

# If do_rigid_regrid_per_detector is False, then we can instead group adjacent
# orders (from the same detector) together when doing the cross-correlation.
# For example, setting this to 2 would use pairs of orders for computing the CC
n_orders_to_group: 1

# Used to compute the reference phase as n_phase//n_ref_div. For a single
# transit, setting this to 2 would take the 'A' or 'B' position closest to the
# centre of the transit.
n_ref_div: 5

# If True, we use a Molecfit telluric model for the cross-correlation template
# rather than an observed spectrum
use_telluric_model_as_ref: True

# Fill value to use when interpolating tau for the telluric model
tau_fill_value: 0

# Value befow which we consider the pixel sufficiently affected by telluric
# absorption to mask it when continuum normalising.
telluric_trans_bad_px_threshold: 0.5

#------------------------------------------------------------------------------
# Templates for continuum normalisation
#------------------------------------------------------------------------------
# Model stellar spectrum
stellar_template_fits: "data_reduction/WASP107/template_wasp_107.fits"

# Molecfit modelled telluric spectra--one per night to be simulated
molecfit_fits:
- "data_reduction/WASP107/220310_WASP107/molecfit_results/MODEL/BEST_FIT_MODEL.fits"
#- "data_reduction/WASP107/230222_WASP107/molecfit_results/BEST_FIT_MODEL.fits"
- "data_reduction/wasp_107_n2/BEST_FIT_MODEL.fits"
# HACK--note that I need to run the second night through molecfit again