# This file contains the common set of parameters for running SYSREM.
#
# YAML specifications: https://yaml.org/spec/1.2.2/
#
#------------------------------------------------------------------------------
# Data Settings
#------------------------------------------------------------------------------
# Which data cube to load. Just specify the fn_label component, and the path is
# constructed as: <save_path>/transit_data_<label>_n<n_transits>.fits
save_path: ""
n_transit: 2
label: "simulated_R100000_wasp107_CO_H2O_H2S_NH3_stellar_1_telluric_1_planet_0_boost_1_SNR_inf"
#label: "wasp107"

#------------------------------------------------------------------------------
# Template Settings
#------------------------------------------------------------------------------
stellar_template_fits: "data_reduction/WASP107/template_wasp_107.fits"

molecfit_fits:
- "data_reduction/WASP107/220310_WASP107/molecfit_results/MODEL/BEST_FIT_MODEL.fits"
#- "data_reduction/WASP107/230222_WASP107/molecfit_results/BEST_FIT_MODEL.fits"
- "data_reduction/wasp_107_n2/BEST_FIT_MODEL.fits"
# HACK--note that I need to run the second night through molecfit again

# Fill value for missing telluric tau values
tau_fill_value: 0

telluric_trans_bad_px_threshold: 0.5

# Grid of petitRADTRANS planet spectra
template_fits: "templates/WASP107b_prt_lbc/WASP107b_templates_all_R100000.fits"

#------------------------------------------------------------------------------
# SYSREM Settings
#------------------------------------------------------------------------------
# Sigma thresholds for sigma clipping
sigma_threshold_phase: 5.0
sigma_threshold_spectral: 5.0

# Which transit to run on.
# TODO: note that this will probably eventually be removed, but now is useful
# for testing.
transit_i: 0

# Number of iterations to run SYSREM for
n_sysrem_iter: 5

# These segments will be masked out completely. For K2148 this is 2.0-2.07um
segments_to_mask_completely: [2, 3, 4]

# Alternatively, for testing purposes we can just plain cut drop the number
# of segments to speed things up.
do_drop_segments: False
segments_to_keep: [15, 16, 17]

# Set to true if we want to test things by cross-correlating with a telluric
# template spectrum rather than one from a planet
cc_with_telluric: False

# Convergence threshold for each SYSREM iteration
sysrem_convergence_tol: 1.0E-6

# Maximum number of iterations to run while converging SYSREM
sysrem_max_convergence_iter: 100

# Function used to assess convergence: ['mean', 'median', 'min', 'max']
sysrem_diff_method: "max"

#------------------------------------------------------------------------------
# Cross Correlation Settings
#------------------------------------------------------------------------------
# Step size for the cross-correlation in km/s
cc_rv_step: 0.25

# Minimum and maximum extents of the cross correlation in km/s
cc_rv_lims: [-50,50]

#------------------------------------------------------------------------------
# Kp-Vsys Settings
#------------------------------------------------------------------------------
# Step size for the Kp-Vsys map in km/s
Kp_step: 1.0

# Minimum and maximum extents of the Kp-Vsys map in km/s
Kp_lims: [0,400]